name = "RossTheme"
license = "GNU General Public License v3.0"
licenselink = "https://github.com/RossKnapman/HugoTheme/blob/master/LICENSE"
description = ""
tags = []
features = []

[author]
  name = "Ross Knapman"
  homepage = "https://www.rossknapman.com"